# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
