# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0006_articles_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=301)),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='url',
            new_name='article_url',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='links',
        ),
        migrations.AddField(
            model_name='url',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biasapp.Articles'),
        ),
    ]
