# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0007_auto_20170315_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
