# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0013_auto_20170326_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='negative',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='url',
            name='neutral',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='url',
            name='positive',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
