# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0017_auto_20170326_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='negative',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='url',
            name='neutral',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='url',
            name='positive',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
