# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0020_auto_20170327_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='calc_bias',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='articles',
            name='social_meida_ref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='unknown_links',
            field=models.IntegerField(default=0),
        ),
    ]
