# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0021_auto_20170327_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='total_links',
            field=models.IntegerField(default=0),
        ),
    ]
