# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0022_articles_total_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='self_reference',
            field=models.IntegerField(default=0),
        ),
    ]
