# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0023_articles_self_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='total_links',
            field=models.IntegerField(default=1),
        ),
    ]
