# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0025_auto_20170327_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='website',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
