# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0026_articles_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_url',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='url',
            name='link_url',
            field=models.CharField(max_length=700),
        ),
    ]
