# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0027_auto_20170401_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
