# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0029_similararticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='edu_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='gov_links',
            field=models.IntegerField(default=0),
        ),
    ]
