# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasapp', '0032_auto_20170428_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='all_sides_bias',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
    ]
